version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: backend-web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - collected_static:/app/collected_static
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://backend-redis:6379/0
      DJANGO_SETTINGS_MODULE: backend.settings
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: backend-celery
    command: celery -A backend worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://backend-redis:6379/0
      DJANGO_SETTINGS_MODULE: backend.settings
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: backend-redis
    ports:
      - "6379:6379"

volumes:
  collected_static: {}

