# Generated by Django 5.2.6 on 2025-10-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_customuser_avatar_customuser_avatar_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
